# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1020, 777)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/graph.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("\n"
"*{color:white;}\n"
"#centralwidget{\n"
"    background-color:rgb(24,24,36);\n"
"\n"
"}\n"
"\n"
"#frame_application_header{\n"
"    background-color:rgb(9,5,13)\n"
"\n"
"}\n"
"\n"
"#frame_left_side_panel{\n"
"    background-color:rgb(9,5,13)\n"
"\n"
"}\n"
"\n"
"#frame_header_panel{\n"
"    background-color:rgb(24,24,36)\n"
"\n"
"}\n"
"\n"
"\n"
"#btn_minimize{\n"
"    margin-right:11px;\n"
"    min-width:80px;\n"
"}\n"
"\n"
"\n"
"#btn_close{\n"
"    margin-right:11px;\n"
"    min-width:80px;\n"
"}\n"
"\n"
"\n"
"\n"
"#scrollAreaWidgetContents{\n"
"    background-color:rgb(9,5,13)\n"
"}\n"
"\n"
"QLineEdit{\n"
"    \n"
"    border:2px solid #222831;\n"
"    \n"
"    border-radius:3px;\n"
"    color:#FFF;\n"
"    background-color: #222831;\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    \n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QSlider::groove:horizontal {\n"
"    border: 1px solid #64748B;\n"
"    height: 13px;\n"
"    background: #1E293B;\n"
"    border-radius:3px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background:#FFD369;\n"
"    border: 1px solid #1E293B;\n"
"    width: 8px;\n"
"    margin: -8px 0;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: #1E293B;\n"
"    height: 14px;\n"
"    margin: 0px 20px 0 20px;\n"
"    border-radius:0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background-color:#334155;\n"
"    min-width: 30px;\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background-color:#FACC15;\n"
"   \n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:pressed {\n"
"    background-color:#EAB308;\n"
"   \n"
"}\n"
"\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background-color:#0F172A;\n"
"    width: 20px;\n"
"    border-top-right-radius:3px;\n"
"    border-bottom-right-radius:3px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal:hover {\n"
"           background-color:rgb(255,0,127);\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal:pressed {\n"
"      background-color:rgb(185,0,92);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background-color:#0F172A;\n"
"    width: 20px;\n"
"    border-top-left-radius:3px;\n"
"    border-bottom-left-radius:3px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:horizontal:hover {\n"
"           background-color:rgb(255,0,127);\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal:pressed {\n"
"      background-color:rgb(185,0,92);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"QScrollBar:left-arrow:horizontal, QScrollBar::right-arrow:horizontal {\n"
"   \n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 23px;\n"
"    height: 23px;\n"
"    background-color:white;\n"
"    border-radius:4px;\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::unchecked {\n"
"    image: url(:/icons/icons/radio-unchecked.png);\n"
"}\n"
"\n"
"QRadioButton::indicator::checked {\n"
"    image: url(:/icons/icons/radio-checked.png);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    border-radius: 3px;\n"
"    background-color: rgb(34,36,44);\n"
"    min-width: 100px;\n"
"    color:white;\n"
"    padding:0px 5px 0 5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(34, 40, 49);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(57, 62, 70);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        MainWindow.setIconSize(QtCore.QSize(40, 40))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setMinimumSize(QtCore.QSize(1020, 777))
        self.centralwidget.setStyleSheet("\n"
"#centralwidget{\n"
"    background-color:rgb(24,24,36);\n"
"    border-radius:8px;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_application_header = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_application_header.sizePolicy().hasHeightForWidth())
        self.frame_application_header.setSizePolicy(sizePolicy)
        self.frame_application_header.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_application_header.setStyleSheet("")
        self.frame_application_header.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_application_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_application_header.setObjectName("frame_application_header")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_application_header)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem = QtWidgets.QSpacerItem(16, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.label_application_icon = QtWidgets.QLabel(self.frame_application_header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_application_icon.sizePolicy().hasHeightForWidth())
        self.label_application_icon.setSizePolicy(sizePolicy)
        self.label_application_icon.setMinimumSize(QtCore.QSize(50, 50))
        self.label_application_icon.setMaximumSize(QtCore.QSize(50, 50))
        self.label_application_icon.setStyleSheet("border-image: url(:/icons/icons/graph.png);")
        self.label_application_icon.setText("")
        self.label_application_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.label_application_icon.setObjectName("label_application_icon")
        self.horizontalLayout_11.addWidget(self.label_application_icon)
        self.label_application_title = QtWidgets.QLabel(self.frame_application_header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_application_title.sizePolicy().hasHeightForWidth())
        self.label_application_title.setSizePolicy(sizePolicy)
        self.label_application_title.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_application_title.setFont(font)
        self.label_application_title.setIndent(18)
        self.label_application_title.setObjectName("label_application_title")
        self.horizontalLayout_11.addWidget(self.label_application_title)
        self.btn_minimize = QtWidgets.QPushButton(self.frame_application_header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_minimize.sizePolicy().hasHeightForWidth())
        self.btn_minimize.setSizePolicy(sizePolicy)
        self.btn_minimize.setMinimumSize(QtCore.QSize(71, 50))
        self.btn_minimize.setMaximumSize(QtCore.QSize(60, 16777215))
        self.btn_minimize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_minimize.setStyleSheet("min-width:50px;\n"
"min-height:50px;\n"
"border-radius:3px;")
        self.btn_minimize.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_minimize.setIcon(icon1)
        self.btn_minimize.setIconSize(QtCore.QSize(25, 25))
        self.btn_minimize.setFlat(False)
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout_11.addWidget(self.btn_minimize)
        self.btn_restore_maximize = QtWidgets.QPushButton(self.frame_application_header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_restore_maximize.sizePolicy().hasHeightForWidth())
        self.btn_restore_maximize.setSizePolicy(sizePolicy)
        self.btn_restore_maximize.setMinimumSize(QtCore.QSize(60, 50))
        self.btn_restore_maximize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_restore_maximize.setStyleSheet("min-width:50px;\n"
"min-height:50px;\n"
"border-radius:3px;")
        self.btn_restore_maximize.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_restore_maximize.setIcon(icon2)
        self.btn_restore_maximize.setIconSize(QtCore.QSize(25, 25))
        self.btn_restore_maximize.setObjectName("btn_restore_maximize")
        self.horizontalLayout_11.addWidget(self.btn_restore_maximize)
        spacerItem1 = QtWidgets.QSpacerItem(9, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.btn_close = QtWidgets.QPushButton(self.frame_application_header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_close.sizePolicy().hasHeightForWidth())
        self.btn_close.setSizePolicy(sizePolicy)
        self.btn_close.setMinimumSize(QtCore.QSize(71, 50))
        self.btn_close.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_close.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_close.setStyleSheet("min-width:50px;\n"
"min-height:50px;\n"
"border-radius:3px;")
        self.btn_close.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon3)
        self.btn_close.setIconSize(QtCore.QSize(20, 20))
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_11.addWidget(self.btn_close)
        self.verticalLayout_15.addWidget(self.frame_application_header)
        self.frame_main_panel = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_main_panel.sizePolicy().hasHeightForWidth())
        self.frame_main_panel.setSizePolicy(sizePolicy)
        self.frame_main_panel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_main_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main_panel.setObjectName("frame_main_panel")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_main_panel)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_left_side_panel = QtWidgets.QFrame(self.frame_main_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_left_side_panel.sizePolicy().hasHeightForWidth())
        self.frame_left_side_panel.setSizePolicy(sizePolicy)
        self.frame_left_side_panel.setMinimumSize(QtCore.QSize(300, 600))
        self.frame_left_side_panel.setMaximumSize(QtCore.QSize(300, 66666))
        self.frame_left_side_panel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_left_side_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_side_panel.setObjectName("frame_left_side_panel")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_left_side_panel)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.frame_animation_speed = QtWidgets.QFrame(self.frame_left_side_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_animation_speed.sizePolicy().hasHeightForWidth())
        self.frame_animation_speed.setSizePolicy(sizePolicy)
        self.frame_animation_speed.setMinimumSize(QtCore.QSize(306, 80))
        self.frame_animation_speed.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_animation_speed.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_animation_speed.setObjectName("frame_animation_speed")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_animation_speed)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lbl_animation_speed = QtWidgets.QLabel(self.frame_animation_speed)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_animation_speed.sizePolicy().hasHeightForWidth())
        self.lbl_animation_speed.setSizePolicy(sizePolicy)
        self.lbl_animation_speed.setObjectName("lbl_animation_speed")
        self.verticalLayout_3.addWidget(self.lbl_animation_speed, 0, QtCore.Qt.AlignHCenter)
        self.horizontalSlider_animation_speed = QtWidgets.QSlider(self.frame_animation_speed)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_animation_speed.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_animation_speed.setSizePolicy(sizePolicy)
        self.horizontalSlider_animation_speed.setMinimumSize(QtCore.QSize(280, 0))
        self.horizontalSlider_animation_speed.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider_animation_speed.setMinimum(10)
        self.horizontalSlider_animation_speed.setMaximum(160)
        self.horizontalSlider_animation_speed.setSingleStep(10)
        self.horizontalSlider_animation_speed.setPageStep(10)
        self.horizontalSlider_animation_speed.setProperty("value", 60)
        self.horizontalSlider_animation_speed.setTracking(True)
        self.horizontalSlider_animation_speed.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_animation_speed.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider_animation_speed.setTickInterval(10)
        self.horizontalSlider_animation_speed.setObjectName("horizontalSlider_animation_speed")
        self.verticalLayout_3.addWidget(self.horizontalSlider_animation_speed, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.frame_animation_speed)
        self.frame_manuel_random_list_title = QtWidgets.QFrame(self.frame_left_side_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_manuel_random_list_title.sizePolicy().hasHeightForWidth())
        self.frame_manuel_random_list_title.setSizePolicy(sizePolicy)
        self.frame_manuel_random_list_title.setMinimumSize(QtCore.QSize(306, 60))
        self.frame_manuel_random_list_title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_manuel_random_list_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_manuel_random_list_title.setObjectName("frame_manuel_random_list_title")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_manuel_random_list_title)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem3 = QtWidgets.QSpacerItem(20, 9, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem3)
        self.lbl_list_create_title = QtWidgets.QLabel(self.frame_manuel_random_list_title)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_list_create_title.sizePolicy().hasHeightForWidth())
        self.lbl_list_create_title.setSizePolicy(sizePolicy)
        self.lbl_list_create_title.setMinimumSize(QtCore.QSize(0, 30))
        self.lbl_list_create_title.setObjectName("lbl_list_create_title")
        self.verticalLayout_7.addWidget(self.lbl_list_create_title, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.frame_manuel_random_list_title)
        self.frame_manuel_list_container = QtWidgets.QFrame(self.frame_left_side_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_manuel_list_container.sizePolicy().hasHeightForWidth())
        self.frame_manuel_list_container.setSizePolicy(sizePolicy)
        self.frame_manuel_list_container.setMinimumSize(QtCore.QSize(309, 200))
        self.frame_manuel_list_container.setMaximumSize(QtCore.QSize(263, 16777215))
        self.frame_manuel_list_container.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_manuel_list_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_manuel_list_container.setObjectName("frame_manuel_list_container")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_manuel_list_container)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem4)
        self.radioButton_manuel_list = QtWidgets.QRadioButton(self.frame_manuel_list_container)
        self.radioButton_manuel_list.setMinimumSize(QtCore.QSize(0, 0))
        self.radioButton_manuel_list.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton_manuel_list.setAutoFillBackground(False)
        self.radioButton_manuel_list.setCheckable(True)
        self.radioButton_manuel_list.setObjectName("radioButton_manuel_list")
        self.verticalLayout_4.addWidget(self.radioButton_manuel_list, 0, QtCore.Qt.AlignHCenter)
        spacerItem5 = QtWidgets.QSpacerItem(20, 6, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem5)
        self.scrollArea = QtWidgets.QScrollArea(self.frame_manuel_list_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(280, 100))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 110))
        self.scrollArea.setStyleSheet("background:#737373;\n"
"border-radius:3px\n"
"")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 280, 86))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_manuel_list = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_manuel_list.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_manuel_list.sizePolicy().hasHeightForWidth())
        self.frame_manuel_list.setSizePolicy(sizePolicy)
        self.frame_manuel_list.setMinimumSize(QtCore.QSize(50, 50))
        self.frame_manuel_list.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_manuel_list.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_manuel_list.setObjectName("frame_manuel_list")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_manuel_list)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_manuel_list_0 = QtWidgets.QLineEdit(self.frame_manuel_list)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_manuel_list_0.sizePolicy().hasHeightForWidth())
        self.lineEdit_manuel_list_0.setSizePolicy(sizePolicy)
        self.lineEdit_manuel_list_0.setMinimumSize(QtCore.QSize(50, 50))
        self.lineEdit_manuel_list_0.setMaximumSize(QtCore.QSize(50, 50))
        self.lineEdit_manuel_list_0.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit_manuel_list_0.setStyleSheet("border-color:#A8A29E;")
        self.lineEdit_manuel_list_0.setText("")
        self.lineEdit_manuel_list_0.setMaxLength(5)
        self.lineEdit_manuel_list_0.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_manuel_list_0.setObjectName("lineEdit_manuel_list_0")
        self.horizontalLayout.addWidget(self.lineEdit_manuel_list_0)
        self.verticalLayout.addWidget(self.frame_manuel_list, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea, 0, QtCore.Qt.AlignHCenter)
        self.frame_manuel_list_buttons = QtWidgets.QFrame(self.frame_manuel_list_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_manuel_list_buttons.sizePolicy().hasHeightForWidth())
        self.frame_manuel_list_buttons.setSizePolicy(sizePolicy)
        self.frame_manuel_list_buttons.setMinimumSize(QtCore.QSize(100, 64))
        self.frame_manuel_list_buttons.setMaximumSize(QtCore.QSize(306, 16777215))
        self.frame_manuel_list_buttons.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_manuel_list_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_manuel_list_buttons.setObjectName("frame_manuel_list_buttons")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_manuel_list_buttons)
        self.horizontalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.btn_manuel_list_remove_item = QtWidgets.QPushButton(self.frame_manuel_list_buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_manuel_list_remove_item.sizePolicy().hasHeightForWidth())
        self.btn_manuel_list_remove_item.setSizePolicy(sizePolicy)
        self.btn_manuel_list_remove_item.setMinimumSize(QtCore.QSize(110, 50))
        self.btn_manuel_list_remove_item.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btn_manuel_list_remove_item.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_manuel_list_remove_item.setStyleSheet("\n"
"min-width:100px;\n"
"border-radius:3px;")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/minus0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_manuel_list_remove_item.setIcon(icon4)
        self.btn_manuel_list_remove_item.setIconSize(QtCore.QSize(30, 30))
        self.btn_manuel_list_remove_item.setObjectName("btn_manuel_list_remove_item")
        self.horizontalLayout_3.addWidget(self.btn_manuel_list_remove_item, 0, QtCore.Qt.AlignHCenter)
        spacerItem7 = QtWidgets.QSpacerItem(9, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.btn_manuel_list_remove_all_items = QtWidgets.QPushButton(self.frame_manuel_list_buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_manuel_list_remove_all_items.sizePolicy().hasHeightForWidth())
        self.btn_manuel_list_remove_all_items.setSizePolicy(sizePolicy)
        self.btn_manuel_list_remove_all_items.setMinimumSize(QtCore.QSize(110, 50))
        self.btn_manuel_list_remove_all_items.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btn_manuel_list_remove_all_items.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_manuel_list_remove_all_items.setStyleSheet("\n"
"\n"
"#btn_manuel_list_remove_all_items\n"
"{\n"
"\n"
"min-width:100px;\n"
"border-radius:3px;\n"
"    \n"
"}\n"
"\n"
"\n"
"#btn_manuel_list_remove_all_items:hover\n"
"{\n"
"\n"
"\n"
"    \n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/dustbin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_manuel_list_remove_all_items.setIcon(icon5)
        self.btn_manuel_list_remove_all_items.setIconSize(QtCore.QSize(30, 30))
        self.btn_manuel_list_remove_all_items.setObjectName("btn_manuel_list_remove_all_items")
        self.horizontalLayout_3.addWidget(self.btn_manuel_list_remove_all_items, 0, QtCore.Qt.AlignHCenter)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.verticalLayout_4.addWidget(self.frame_manuel_list_buttons)
        self.verticalLayout_2.addWidget(self.frame_manuel_list_container)
        self.frame_random_list_container = QtWidgets.QFrame(self.frame_left_side_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_random_list_container.sizePolicy().hasHeightForWidth())
        self.frame_random_list_container.setSizePolicy(sizePolicy)
        self.frame_random_list_container.setMinimumSize(QtCore.QSize(306, 193))
        self.frame_random_list_container.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_random_list_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_random_list_container.setObjectName("frame_random_list_container")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_random_list_container)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem9 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem9)
        self.radioButton_random_list = QtWidgets.QRadioButton(self.frame_random_list_container)
        self.radioButton_random_list.setMinimumSize(QtCore.QSize(0, 0))
        self.radioButton_random_list.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton_random_list.setStyleSheet("")
        self.radioButton_random_list.setCheckable(True)
        self.radioButton_random_list.setObjectName("radioButton_random_list")
        self.verticalLayout_5.addWidget(self.radioButton_random_list, 0, QtCore.Qt.AlignHCenter)
        spacerItem10 = QtWidgets.QSpacerItem(20, 6, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem10)
        self.frame_random_list = QtWidgets.QFrame(self.frame_random_list_container)
        self.frame_random_list.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_random_list.sizePolicy().hasHeightForWidth())
        self.frame_random_list.setSizePolicy(sizePolicy)
        self.frame_random_list.setMinimumSize(QtCore.QSize(200, 100))
        self.frame_random_list.setMaximumSize(QtCore.QSize(273, 16777215))
        self.frame_random_list.setStyleSheet("background:#737373;\n"
"padding:0 3px 3px 3px;\n"
"border-radius:3px;")
        self.frame_random_list.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_random_list.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_random_list.setObjectName("frame_random_list")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_random_list)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_random_list_label_container = QtWidgets.QFrame(self.frame_random_list)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_random_list_label_container.sizePolicy().hasHeightForWidth())
        self.frame_random_list_label_container.setSizePolicy(sizePolicy)
        self.frame_random_list_label_container.setMinimumSize(QtCore.QSize(213, 30))
        self.frame_random_list_label_container.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_random_list_label_container.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_random_list_label_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_random_list_label_container.setObjectName("frame_random_list_label_container")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_random_list_label_container)
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(11)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lbl_min = QtWidgets.QLabel(self.frame_random_list_label_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_min.sizePolicy().hasHeightForWidth())
        self.lbl_min.setSizePolicy(sizePolicy)
        self.lbl_min.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_min.setFont(font)
        self.lbl_min.setStyleSheet("")
        self.lbl_min.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_min.setObjectName("lbl_min")
        self.horizontalLayout_6.addWidget(self.lbl_min)
        self.lbl_max = QtWidgets.QLabel(self.frame_random_list_label_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_max.sizePolicy().hasHeightForWidth())
        self.lbl_max.setSizePolicy(sizePolicy)
        self.lbl_max.setMinimumSize(QtCore.QSize(62, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_max.setFont(font)
        self.lbl_max.setStyleSheet("")
        self.lbl_max.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_max.setObjectName("lbl_max")
        self.horizontalLayout_6.addWidget(self.lbl_max)
        self.lbl_length = QtWidgets.QLabel(self.frame_random_list_label_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_length.sizePolicy().hasHeightForWidth())
        self.lbl_length.setSizePolicy(sizePolicy)
        self.lbl_length.setMinimumSize(QtCore.QSize(73, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_length.setFont(font)
        self.lbl_length.setStyleSheet("margin-left:3px;")
        self.lbl_length.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_length.setObjectName("lbl_length")
        self.horizontalLayout_6.addWidget(self.lbl_length)
        self.verticalLayout_6.addWidget(self.frame_random_list_label_container)
        self.frame_random_list_lineEdit_container = QtWidgets.QFrame(self.frame_random_list)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_random_list_lineEdit_container.sizePolicy().hasHeightForWidth())
        self.frame_random_list_lineEdit_container.setSizePolicy(sizePolicy)
        self.frame_random_list_lineEdit_container.setMinimumSize(QtCore.QSize(213, 60))
        self.frame_random_list_lineEdit_container.setMaximumSize(QtCore.QSize(160, 16777215))
        self.frame_random_list_lineEdit_container.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_random_list_lineEdit_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_random_list_lineEdit_container.setObjectName("frame_random_list_lineEdit_container")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_random_list_lineEdit_container)
        self.horizontalLayout_7.setContentsMargins(11, 3, 11, 3)
        self.horizontalLayout_7.setSpacing(7)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEdit_random_list_min = QtWidgets.QLineEdit(self.frame_random_list_lineEdit_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_random_list_min.sizePolicy().hasHeightForWidth())
        self.lineEdit_random_list_min.setSizePolicy(sizePolicy)
        self.lineEdit_random_list_min.setMinimumSize(QtCore.QSize(50, 50))
        self.lineEdit_random_list_min.setMaximumSize(QtCore.QSize(50, 50))
        self.lineEdit_random_list_min.setStyleSheet("border-color:#A8A29E;")
        self.lineEdit_random_list_min.setMaxLength(5)
        self.lineEdit_random_list_min.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_random_list_min.setObjectName("lineEdit_random_list_min")
        self.horizontalLayout_7.addWidget(self.lineEdit_random_list_min)
        self.lineEdit_random_list_max = QtWidgets.QLineEdit(self.frame_random_list_lineEdit_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_random_list_max.sizePolicy().hasHeightForWidth())
        self.lineEdit_random_list_max.setSizePolicy(sizePolicy)
        self.lineEdit_random_list_max.setMinimumSize(QtCore.QSize(50, 50))
        self.lineEdit_random_list_max.setMaximumSize(QtCore.QSize(50, 50))
        self.lineEdit_random_list_max.setStyleSheet("border-color:#A8A29E;")
        self.lineEdit_random_list_max.setMaxLength(5)
        self.lineEdit_random_list_max.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_random_list_max.setObjectName("lineEdit_random_list_max")
        self.horizontalLayout_7.addWidget(self.lineEdit_random_list_max, 0, QtCore.Qt.AlignHCenter)
        self.lineEdit_random_list_length = QtWidgets.QLineEdit(self.frame_random_list_lineEdit_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_random_list_length.sizePolicy().hasHeightForWidth())
        self.lineEdit_random_list_length.setSizePolicy(sizePolicy)
        self.lineEdit_random_list_length.setMinimumSize(QtCore.QSize(50, 50))
        self.lineEdit_random_list_length.setMaximumSize(QtCore.QSize(50, 50))
        self.lineEdit_random_list_length.setStyleSheet("border-color:#A8A29E;")
        self.lineEdit_random_list_length.setMaxLength(5)
        self.lineEdit_random_list_length.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_random_list_length.setObjectName("lineEdit_random_list_length")
        self.horizontalLayout_7.addWidget(self.lineEdit_random_list_length)
        self.verticalLayout_6.addWidget(self.frame_random_list_lineEdit_container)
        self.verticalLayout_5.addWidget(self.frame_random_list, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.lbl_validation_message = QtWidgets.QLabel(self.frame_random_list_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_validation_message.sizePolicy().hasHeightForWidth())
        self.lbl_validation_message.setSizePolicy(sizePolicy)
        self.lbl_validation_message.setMinimumSize(QtCore.QSize(0, 60))
        self.lbl_validation_message.setText("")
        self.lbl_validation_message.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_validation_message.setWordWrap(True)
        self.lbl_validation_message.setObjectName("lbl_validation_message")
        self.verticalLayout_5.addWidget(self.lbl_validation_message, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.frame_random_list_container)
        spacerItem11 = QtWidgets.QSpacerItem(20, 63, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem11)
        self.horizontalLayout_10.addWidget(self.frame_left_side_panel)
        self.frame_right_main_panel = QtWidgets.QFrame(self.frame_main_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_right_main_panel.sizePolicy().hasHeightForWidth())
        self.frame_right_main_panel.setSizePolicy(sizePolicy)
        self.frame_right_main_panel.setMinimumSize(QtCore.QSize(720, 666))
        self.frame_right_main_panel.setStyleSheet("")
        self.frame_right_main_panel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_right_main_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_right_main_panel.setObjectName("frame_right_main_panel")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_right_main_panel)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_header_panel = QtWidgets.QFrame(self.frame_right_main_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_header_panel.sizePolicy().hasHeightForWidth())
        self.frame_header_panel.setSizePolicy(sizePolicy)
        self.frame_header_panel.setMinimumSize(QtCore.QSize(696, 200))
        self.frame_header_panel.setMaximumSize(QtCore.QSize(1000, 208))
        self.frame_header_panel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_header_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_header_panel.setObjectName("frame_header_panel")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_header_panel)
        self.horizontalLayout_9.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_sorting_options = QtWidgets.QFrame(self.frame_header_panel)
        self.frame_sorting_options.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_sorting_options.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_sorting_options.setObjectName("frame_sorting_options")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_sorting_options)
        self.horizontalLayout_8.setContentsMargins(8, 8, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_sorting_algorithm_container = QtWidgets.QFrame(self.frame_sorting_options)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_sorting_algorithm_container.sizePolicy().hasHeightForWidth())
        self.frame_sorting_algorithm_container.setSizePolicy(sizePolicy)
        self.frame_sorting_algorithm_container.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_sorting_algorithm_container.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_sorting_algorithm_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_sorting_algorithm_container.setObjectName("frame_sorting_algorithm_container")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_sorting_algorithm_container)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lbl_sorting_algorithms_title = QtWidgets.QLabel(self.frame_sorting_algorithm_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_sorting_algorithms_title.sizePolicy().hasHeightForWidth())
        self.lbl_sorting_algorithms_title.setSizePolicy(sizePolicy)
        self.lbl_sorting_algorithms_title.setObjectName("lbl_sorting_algorithms_title")
        self.verticalLayout_8.addWidget(self.lbl_sorting_algorithms_title, 0, QtCore.Qt.AlignHCenter)
        self.frame_sorting_algorithms = QtWidgets.QFrame(self.frame_sorting_algorithm_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_sorting_algorithms.sizePolicy().hasHeightForWidth())
        self.frame_sorting_algorithms.setSizePolicy(sizePolicy)
        self.frame_sorting_algorithms.setMinimumSize(QtCore.QSize(0, 160))
        self.frame_sorting_algorithms.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_sorting_algorithms.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_sorting_algorithms.setObjectName("frame_sorting_algorithms")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_sorting_algorithms)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.radioButton_selection_sort = QtWidgets.QRadioButton(self.frame_sorting_algorithms)
        self.radioButton_selection_sort.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton_selection_sort.setObjectName("radioButton_selection_sort")
        self.verticalLayout_9.addWidget(self.radioButton_selection_sort)
        self.radioButton_bubble_sort = QtWidgets.QRadioButton(self.frame_sorting_algorithms)
        self.radioButton_bubble_sort.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton_bubble_sort.setChecked(True)
        self.radioButton_bubble_sort.setObjectName("radioButton_bubble_sort")
        self.verticalLayout_9.addWidget(self.radioButton_bubble_sort)
        self.radioButton_insertion_sort = QtWidgets.QRadioButton(self.frame_sorting_algorithms)
        self.radioButton_insertion_sort.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton_insertion_sort.setObjectName("radioButton_insertion_sort")
        self.verticalLayout_9.addWidget(self.radioButton_insertion_sort)
        self.radioButton_merge_sort = QtWidgets.QRadioButton(self.frame_sorting_algorithms)
        self.radioButton_merge_sort.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton_merge_sort.setObjectName("radioButton_merge_sort")
        self.verticalLayout_9.addWidget(self.radioButton_merge_sort)
        self.radioButton_quick_sort = QtWidgets.QRadioButton(self.frame_sorting_algorithms)
        self.radioButton_quick_sort.setEnabled(True)
        self.radioButton_quick_sort.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton_quick_sort.setObjectName("radioButton_quick_sort")
        self.verticalLayout_9.addWidget(self.radioButton_quick_sort)
        self.verticalLayout_8.addWidget(self.frame_sorting_algorithms)
        spacerItem12 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_8.addItem(spacerItem12)
        self.horizontalLayout_8.addWidget(self.frame_sorting_algorithm_container)
        self.frame_graph_type_container = QtWidgets.QFrame(self.frame_sorting_options)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_graph_type_container.sizePolicy().hasHeightForWidth())
        self.frame_graph_type_container.setSizePolicy(sizePolicy)
        self.frame_graph_type_container.setMinimumSize(QtCore.QSize(157, 0))
        self.frame_graph_type_container.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_graph_type_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_graph_type_container.setObjectName("frame_graph_type_container")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_graph_type_container)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lbl_sorting_graph_type_title = QtWidgets.QLabel(self.frame_graph_type_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_sorting_graph_type_title.sizePolicy().hasHeightForWidth())
        self.lbl_sorting_graph_type_title.setSizePolicy(sizePolicy)
        self.lbl_sorting_graph_type_title.setObjectName("lbl_sorting_graph_type_title")
        self.verticalLayout_10.addWidget(self.lbl_sorting_graph_type_title, 0, QtCore.Qt.AlignHCenter)
        self.frame_sorting_graph_type = QtWidgets.QFrame(self.frame_graph_type_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_sorting_graph_type.sizePolicy().hasHeightForWidth())
        self.frame_sorting_graph_type.setSizePolicy(sizePolicy)
        self.frame_sorting_graph_type.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_sorting_graph_type.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_sorting_graph_type.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_sorting_graph_type.setObjectName("frame_sorting_graph_type")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_sorting_graph_type)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.radioButton_scatter_graph = QtWidgets.QRadioButton(self.frame_sorting_graph_type)
        self.radioButton_scatter_graph.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton_scatter_graph.setObjectName("radioButton_scatter_graph")
        self.verticalLayout_11.addWidget(self.radioButton_scatter_graph)
        self.radioButton_bar_graph = QtWidgets.QRadioButton(self.frame_sorting_graph_type)
        self.radioButton_bar_graph.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton_bar_graph.setChecked(True)
        self.radioButton_bar_graph.setObjectName("radioButton_bar_graph")
        self.verticalLayout_11.addWidget(self.radioButton_bar_graph)
        self.radioButton_stem_graph = QtWidgets.QRadioButton(self.frame_sorting_graph_type)
        self.radioButton_stem_graph.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton_stem_graph.setObjectName("radioButton_stem_graph")
        self.verticalLayout_11.addWidget(self.radioButton_stem_graph)
        self.verticalLayout_10.addWidget(self.frame_sorting_graph_type)
        spacerItem13 = QtWidgets.QSpacerItem(20, 59, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_10.addItem(spacerItem13)
        self.horizontalLayout_8.addWidget(self.frame_graph_type_container)
        self.horizontalLayout_9.addWidget(self.frame_sorting_options)
        self.frame_control_buttons = QtWidgets.QFrame(self.frame_header_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_control_buttons.sizePolicy().hasHeightForWidth())
        self.frame_control_buttons.setSizePolicy(sizePolicy)
        self.frame_control_buttons.setMinimumSize(QtCore.QSize(100, 128))
        self.frame_control_buttons.setMaximumSize(QtCore.QSize(288, 16777215))
        self.frame_control_buttons.setStyleSheet("")
        self.frame_control_buttons.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_control_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_control_buttons.setObjectName("frame_control_buttons")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_control_buttons)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(7)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_2 = QtWidgets.QFrame(self.frame_control_buttons)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(7)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.btn_create = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_create.sizePolicy().hasHeightForWidth())
        self.btn_create.setSizePolicy(sizePolicy)
        self.btn_create.setMinimumSize(QtCore.QSize(110, 50))
        self.btn_create.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_create.setStyleSheet("width:100px;\n"
"background:#737373;\n"
"border-radius:3px;")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/create.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_create.setIcon(icon6)
        self.btn_create.setIconSize(QtCore.QSize(30, 30))
        self.btn_create.setObjectName("btn_create")
        self.verticalLayout_14.addWidget(self.btn_create, 0, QtCore.Qt.AlignHCenter)
        self.btn_start = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_start.sizePolicy().hasHeightForWidth())
        self.btn_start.setSizePolicy(sizePolicy)
        self.btn_start.setMinimumSize(QtCore.QSize(110, 50))
        self.btn_start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_start.setStyleSheet("width:100px;\n"
"background:#737373;\n"
"border-radius:3px;")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/play0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_start.setIcon(icon7)
        self.btn_start.setIconSize(QtCore.QSize(27, 27))
        self.btn_start.setObjectName("btn_start")
        self.verticalLayout_14.addWidget(self.btn_start, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_5.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.frame_control_buttons)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(7)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.btn_pause_resume = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_pause_resume.sizePolicy().hasHeightForWidth())
        self.btn_pause_resume.setSizePolicy(sizePolicy)
        self.btn_pause_resume.setMinimumSize(QtCore.QSize(110, 50))
        self.btn_pause_resume.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_pause_resume.setStyleSheet("width:100px;\n"
"background:#737373;\n"
"border-radius:3px;")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_pause_resume.setIcon(icon8)
        self.btn_pause_resume.setIconSize(QtCore.QSize(30, 30))
        self.btn_pause_resume.setCheckable(True)
        self.btn_pause_resume.setChecked(False)
        self.btn_pause_resume.setObjectName("btn_pause_resume")
        self.verticalLayout_12.addWidget(self.btn_pause_resume, 0, QtCore.Qt.AlignHCenter)
        self.btn_reset = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_reset.sizePolicy().hasHeightForWidth())
        self.btn_reset.setSizePolicy(sizePolicy)
        self.btn_reset.setMinimumSize(QtCore.QSize(110, 50))
        self.btn_reset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_reset.setStyleSheet("width:100px;\n"
"background:#737373;\n"
"border-radius:3px;")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_reset.setIcon(icon9)
        self.btn_reset.setIconSize(QtCore.QSize(44, 44))
        self.btn_reset.setObjectName("btn_reset")
        self.verticalLayout_12.addWidget(self.btn_reset, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_5.addWidget(self.frame)
        self.horizontalLayout_9.addWidget(self.frame_control_buttons)
        self.verticalLayout_13.addWidget(self.frame_header_panel)
        self.frame_mpl_container = QtWidgets.QFrame(self.frame_right_main_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_mpl_container.sizePolicy().hasHeightForWidth())
        self.frame_mpl_container.setSizePolicy(sizePolicy)
        self.frame_mpl_container.setMinimumSize(QtCore.QSize(60, 120))
        self.frame_mpl_container.setStyleSheet("background-color:#071e26;\n"
"\n"
"")
        self.frame_mpl_container.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_mpl_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_mpl_container.setObjectName("frame_mpl_container")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_mpl_container)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.MplWidget = MplWidget(self.frame_mpl_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MplWidget.sizePolicy().hasHeightForWidth())
        self.MplWidget.setSizePolicy(sizePolicy)
        self.MplWidget.setMinimumSize(QtCore.QSize(600, 0))
        self.MplWidget.setStyleSheet("border-radius:8px;")
        self.MplWidget.setObjectName("MplWidget")
        self.horizontalLayout_2.addWidget(self.MplWidget)
        self.verticalLayout_13.addWidget(self.frame_mpl_container)
        self.frame_footer = QtWidgets.QFrame(self.frame_right_main_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_footer.sizePolicy().hasHeightForWidth())
        self.frame_footer.setSizePolicy(sizePolicy)
        self.frame_footer.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_footer.setStyleSheet("background-color:#071e26;\n"
"\n"
"border-bottom-right-radius:8px;")
        self.frame_footer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_footer.setObjectName("frame_footer")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_footer)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_complexity_analysis_container = QtWidgets.QFrame(self.frame_footer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_complexity_analysis_container.sizePolicy().hasHeightForWidth())
        self.frame_complexity_analysis_container.setSizePolicy(sizePolicy)
        self.frame_complexity_analysis_container.setMinimumSize(QtCore.QSize(550, 0))
        self.frame_complexity_analysis_container.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_complexity_analysis_container.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_complexity_analysis_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_complexity_analysis_container.setObjectName("frame_complexity_analysis_container")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_complexity_analysis_container)
        self.horizontalLayout_12.setContentsMargins(11, 0, 11, 8)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_complexity_analysis_title = QtWidgets.QFrame(self.frame_complexity_analysis_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_complexity_analysis_title.sizePolicy().hasHeightForWidth())
        self.frame_complexity_analysis_title.setSizePolicy(sizePolicy)
        self.frame_complexity_analysis_title.setMinimumSize(QtCore.QSize(140, 33))
        self.frame_complexity_analysis_title.setMaximumSize(QtCore.QSize(146, 16777215))
        self.frame_complexity_analysis_title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_complexity_analysis_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_complexity_analysis_title.setObjectName("frame_complexity_analysis_title")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_complexity_analysis_title)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.lbl_complexity_analysis_title = QtWidgets.QLabel(self.frame_complexity_analysis_title)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_complexity_analysis_title.sizePolicy().hasHeightForWidth())
        self.lbl_complexity_analysis_title.setSizePolicy(sizePolicy)
        self.lbl_complexity_analysis_title.setObjectName("lbl_complexity_analysis_title")
        self.verticalLayout_16.addWidget(self.lbl_complexity_analysis_title, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_12.addWidget(self.frame_complexity_analysis_title, 0, QtCore.Qt.AlignHCenter)
        self.frame_complexity_analysis = QtWidgets.QFrame(self.frame_complexity_analysis_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_complexity_analysis.sizePolicy().hasHeightForWidth())
        self.frame_complexity_analysis.setSizePolicy(sizePolicy)
        self.frame_complexity_analysis.setMinimumSize(QtCore.QSize(373, 60))
        self.frame_complexity_analysis.setMaximumSize(QtCore.QSize(333, 16777215))
        self.frame_complexity_analysis.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_complexity_analysis.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_complexity_analysis.setObjectName("frame_complexity_analysis")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_complexity_analysis)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame_3 = QtWidgets.QFrame(self.frame_complexity_analysis)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(30, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(11)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lbl_best_case_title = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_best_case_title.sizePolicy().hasHeightForWidth())
        self.lbl_best_case_title.setSizePolicy(sizePolicy)
        self.lbl_best_case_title.setObjectName("lbl_best_case_title")
        self.horizontalLayout_13.addWidget(self.lbl_best_case_title, 0, QtCore.Qt.AlignHCenter)
        self.lbl_average_case_title = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_average_case_title.sizePolicy().hasHeightForWidth())
        self.lbl_average_case_title.setSizePolicy(sizePolicy)
        self.lbl_average_case_title.setObjectName("lbl_average_case_title")
        self.horizontalLayout_13.addWidget(self.lbl_average_case_title, 0, QtCore.Qt.AlignHCenter)
        self.lbl_worst_case_title = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_worst_case_title.sizePolicy().hasHeightForWidth())
        self.lbl_worst_case_title.setSizePolicy(sizePolicy)
        self.lbl_worst_case_title.setObjectName("lbl_worst_case_title")
        self.horizontalLayout_13.addWidget(self.lbl_worst_case_title, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_17.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_complexity_analysis)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(5, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.lbl_best_case_equation = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_best_case_equation.sizePolicy().hasHeightForWidth())
        self.lbl_best_case_equation.setSizePolicy(sizePolicy)
        self.lbl_best_case_equation.setObjectName("lbl_best_case_equation")
        self.horizontalLayout_14.addWidget(self.lbl_best_case_equation, 0, QtCore.Qt.AlignHCenter)
        self.lbl_average_case_equation = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_average_case_equation.sizePolicy().hasHeightForWidth())
        self.lbl_average_case_equation.setSizePolicy(sizePolicy)
        self.lbl_average_case_equation.setObjectName("lbl_average_case_equation")
        self.horizontalLayout_14.addWidget(self.lbl_average_case_equation, 0, QtCore.Qt.AlignHCenter)
        self.lbl_worst_case_equation = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_worst_case_equation.sizePolicy().hasHeightForWidth())
        self.lbl_worst_case_equation.setSizePolicy(sizePolicy)
        self.lbl_worst_case_equation.setObjectName("lbl_worst_case_equation")
        self.horizontalLayout_14.addWidget(self.lbl_worst_case_equation, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_17.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_complexity_analysis)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 13))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.lbl_best_case = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_best_case.sizePolicy().hasHeightForWidth())
        self.lbl_best_case.setSizePolicy(sizePolicy)
        self.lbl_best_case.setObjectName("lbl_best_case")
        self.horizontalLayout_15.addWidget(self.lbl_best_case, 0, QtCore.Qt.AlignHCenter)
        self.lbl_average_case = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_average_case.sizePolicy().hasHeightForWidth())
        self.lbl_average_case.setSizePolicy(sizePolicy)
        self.lbl_average_case.setObjectName("lbl_average_case")
        self.horizontalLayout_15.addWidget(self.lbl_average_case, 0, QtCore.Qt.AlignHCenter)
        self.lbl_worst_case = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_worst_case.sizePolicy().hasHeightForWidth())
        self.lbl_worst_case.setSizePolicy(sizePolicy)
        self.lbl_worst_case.setObjectName("lbl_worst_case")
        self.horizontalLayout_15.addWidget(self.lbl_worst_case, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_17.addWidget(self.frame_5)
        self.horizontalLayout_12.addWidget(self.frame_complexity_analysis)
        self.horizontalLayout_4.addWidget(self.frame_complexity_analysis_container, 0, QtCore.Qt.AlignHCenter)
        self.frame_comparison_count_container = QtWidgets.QFrame(self.frame_footer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_comparison_count_container.sizePolicy().hasHeightForWidth())
        self.frame_comparison_count_container.setSizePolicy(sizePolicy)
        self.frame_comparison_count_container.setMinimumSize(QtCore.QSize(118, 0))
        self.frame_comparison_count_container.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_comparison_count_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_comparison_count_container.setObjectName("frame_comparison_count_container")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_comparison_count_container)
        self.verticalLayout_18.setContentsMargins(8, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.lbl_comparison_count_title = QtWidgets.QLabel(self.frame_comparison_count_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_comparison_count_title.sizePolicy().hasHeightForWidth())
        self.lbl_comparison_count_title.setSizePolicy(sizePolicy)
        self.lbl_comparison_count_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_comparison_count_title.setWordWrap(True)
        self.lbl_comparison_count_title.setObjectName("lbl_comparison_count_title")
        self.verticalLayout_18.addWidget(self.lbl_comparison_count_title, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lbl_comparison_count = QtWidgets.QLabel(self.frame_comparison_count_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_comparison_count.sizePolicy().hasHeightForWidth())
        self.lbl_comparison_count.setSizePolicy(sizePolicy)
        self.lbl_comparison_count.setObjectName("lbl_comparison_count")
        self.verticalLayout_18.addWidget(self.lbl_comparison_count, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_4.addWidget(self.frame_comparison_count_container, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.btn_size_grip = QtWidgets.QPushButton(self.frame_footer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_size_grip.sizePolicy().hasHeightForWidth())
        self.btn_size_grip.setSizePolicy(sizePolicy)
        self.btn_size_grip.setMinimumSize(QtCore.QSize(20, 10))
        self.btn_size_grip.setMaximumSize(QtCore.QSize(10, 10))
        self.btn_size_grip.setStyleSheet("min-width:10px;\n"
"min-height:10px;")
        self.btn_size_grip.setText("")
        self.btn_size_grip.setIconSize(QtCore.QSize(0, 0))
        self.btn_size_grip.setFlat(False)
        self.btn_size_grip.setObjectName("btn_size_grip")
        self.horizontalLayout_4.addWidget(self.btn_size_grip, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.verticalLayout_13.addWidget(self.frame_footer)
        self.horizontalLayout_10.addWidget(self.frame_right_main_panel)
        self.verticalLayout_15.addWidget(self.frame_main_panel)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sıralama Algoritmaları Görselleştiricisi"))
        self.label_application_title.setText(_translate("MainWindow", "Sıralama Algoritmaları Görselleştiricisi"))
        self.lbl_animation_speed.setText(_translate("MainWindow", "Animasyonun Hızı"))
        self.lbl_list_create_title.setText(_translate("MainWindow", "Sıralanacak Listeyi Oluşturun"))
        self.radioButton_manuel_list.setText(_translate("MainWindow", "Manuel Liste ile"))
        self.btn_manuel_list_remove_item.setText(_translate("MainWindow", " Çıkar"))
        self.btn_manuel_list_remove_all_items.setText(_translate("MainWindow", " Temizle"))
        self.radioButton_random_list.setText(_translate("MainWindow", "Rastgele Değerler ile"))
        self.lbl_min.setText(_translate("MainWindow", "Min"))
        self.lbl_max.setText(_translate("MainWindow", "Max"))
        self.lbl_length.setText(_translate("MainWindow", "Uzunluk"))
        self.lbl_sorting_algorithms_title.setText(_translate("MainWindow", "Sıralama Algoritmasını Seçiniz"))
        self.radioButton_selection_sort.setText(_translate("MainWindow", "Seçme Sıralaması"))
        self.radioButton_bubble_sort.setText(_translate("MainWindow", "Kabarcık Sıralaması"))
        self.radioButton_insertion_sort.setText(_translate("MainWindow", "Ekleme Sıralaması"))
        self.radioButton_merge_sort.setText(_translate("MainWindow", "Birleştime Sıralaması"))
        self.radioButton_quick_sort.setText(_translate("MainWindow", "Hızlı Sıralama"))
        self.lbl_sorting_graph_type_title.setText(_translate("MainWindow", "Grafik Türünü Seçiniz"))
        self.radioButton_scatter_graph.setText(_translate("MainWindow", "Dağılım Grafiği"))
        self.radioButton_bar_graph.setText(_translate("MainWindow", "Sütun Grafiği"))
        self.radioButton_stem_graph.setText(_translate("MainWindow", "Kök Grafiği"))
        self.btn_create.setText(_translate("MainWindow", " Oluştur"))
        self.btn_start.setText(_translate("MainWindow", " Başlat"))
        self.btn_pause_resume.setText(_translate("MainWindow", " Durdur"))
        self.btn_reset.setText(_translate("MainWindow", " Sıfırla"))
        self.lbl_complexity_analysis_title.setText(_translate("MainWindow", "Karmaşıklık Analizi :"))
        self.lbl_best_case_title.setText(_translate("MainWindow", "Best Case (Ω)"))
        self.lbl_average_case_title.setText(_translate("MainWindow", "Average Case (θ)"))
        self.lbl_worst_case_title.setText(_translate("MainWindow", "Worst Case (O)"))
        self.lbl_best_case_equation.setText(_translate("MainWindow", "n"))
        self.lbl_average_case_equation.setText(_translate("MainWindow", "n<sup>2</sup>"))
        self.lbl_worst_case_equation.setText(_translate("MainWindow", "n<sup>2</sup>"))
        self.lbl_best_case.setText(_translate("MainWindow", "-"))
        self.lbl_average_case.setText(_translate("MainWindow", "-"))
        self.lbl_worst_case.setText(_translate("MainWindow", "-"))
        self.lbl_comparison_count_title.setText(_translate("MainWindow", "Karşılaştırma Sayısı"))
        self.lbl_comparison_count.setText(_translate("MainWindow", "-"))
from MplWidget import MplWidget
import fonts_rc
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
